version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: minimal

shallow_clone: false

environment:
  PQCLEAN_ONLY_DIFF: 1
  PQCLEAN_SKIP_SCHEMES: sphincs-haraka-128f-robust,sphincs-haraka-192s-robust,sphincs-sha256-128f-robust,sphincs-sha256-192s-robust,sphincs-shake256-128f-robust,sphincs-shake256-192s-robust,sphincs-haraka-128f-simple,sphincs-haraka-192s-simple,sphincs-sha256-128f-simple,sphincs-sha256-192s-simple,sphincs-shake256-128f-simple,sphincs-shake256-192s-simple,sphincs-haraka-128s-robust,sphincs-haraka-256f-robust,sphincs-sha256-128s-robust,sphincs-sha256-256f-robust,sphincs-shake256-128s-robust,sphincs-shake256-256f-robust,sphincs-haraka-128s-simple,sphincs-haraka-256f-simple,sphincs-sha256-128s-simple,sphincs-sha256-256f-simple,sphincs-shake256-128s-simple,sphincs-shake256-256f-simple,sphincs-haraka-192f-robust,sphincs-haraka-256s-robust,sphincs-sha256-192f-robust,sphincs-sha256-256s-robust,sphincs-shake256-192f-robust,sphincs-shake256-256s-robust,sphincs-haraka-192f-simple,sphincs-haraka-256s-simple,sphincs-sha256-192f-simple,sphincs-sha256-256s-simple,sphincs-shake256-192f-simple,sphincs-shake256-256s-simple
  matrix:
    - BITS: 64
      PQCLEAN_ONLY_TYPES: kem
    - BITS: 32
      PQCLEAN_ONLY_TYPES: kem
    - BITS: 64
      PQCLEAN_ONLY_TYPES: sign
    - BITS: 32
      PQCLEAN_ONLY_TYPES: sign

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"
    # Download AStyle 3.1: first enable strong crypto in Invoke-WebRequest
  - ps: Set-ItemProperty -Path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319" -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
  - ps: Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319" -Name "SchUseStrongCrypto" -Value '1' -Type DWord
    # Add Python to PATH
  - set PATH="C:\\Python37";"C:\\Python37\Scripts";%PATH%

build_script:
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --all
  - sh: |
      COMMIT=$(git rev-parse HEAD)
      git checkout $APPVEYOR_REPO_BRANCH
      git reset --hard $COMMIT
  - git diff --name-only origin/master
  - python -m pip install -r requirements.txt
  - cd test
    # Download Astyle to local folder because putting it in PATH doesn't work
  - ps: Invoke-WebRequest -OutFile "astyle.exe" "https://rded.nl/pqclean/AStyle.exe"
    # Run tests
  - python -m pytest --verbose --numprocesses=auto --junitxml=results.xml

on_finish:
  - ps: |
      Try {
          $wc = New-Object 'System.Net.WebClient'
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))
      } Catch {
          Write-Warning "$($error[0])"
      }
